import Head from "next/head";
import React, { useState, useEffect } from "react";
import Image from "next/image";
import { eventArr } from "@/component/data";
import { BsArrowLeft, BsArrowRight } from "react-icons/bs";
import Link from "next/link";
import menuData from "@/component/data";


const Cathering = () => {
  const [indx, setIndx] = useState(0);
  useEffect(() => {
    setTimeout(() => {
      if (indx < eventArr.length - 1) {
        setIndx((prev) => prev + 1);
      } else {
        setIndx(0);
      }
    }, 5000);
  }, [indx]);

  const next = () => {
    if (indx < eventArr.length - 1) {
      setIndx((prev) => prev + 1);
    } else {
      setIndx(0);
    }
  }
  const back = () => {
    if(indx === 0){
      setIndx(eventArr.length - 1)
    }else{
      setIndx((prev) => prev - 1);
    }
  }
  

  const slider = eventArr.map((item, index) => {
    return (
      <div key={index} className="h-96 w-full md:w-9/12 mx-auto mt-16 relative flex items-center justify-center transition-transform duration-200 ease-in-out ">
        <Image src={item.image} alt="dinner" className="w-full h-full" />
        <div className="absolute text-white text-2xl font-bold p-4 bg-black/50 flex justify-between items-center w-full">
          <button onClick={back}>
            <BsArrowLeft />
          </button>
          <p className="">{item.text}</p>
          <button onClick={next}>
            <BsArrowRight />
          </button>
        </div>
      </div>
    );
  });

  return (
    <>
     <Head>
              <title>Cathering</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
  <div className="animate__animated animate__slideInDown">
  {slider[indx]}
  </div>
      
      
      <div className="mx-auto mt-10 text-center">
        <h2 className="text-3xl font-semibold py-4">
          We cater to all sorts of event
        </h2>
        <p className=" w-full md:w-1/2 m-auto px-4">
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Earum, sed
          voluptas facilis facere eveniet nesciunt. Provident explicabo aperiam
          vero repellendus nam fuga eum possimus accusantium in tempora. Porro,
          consequuntur optio? Lorem ipsum, dolor sit amet consectetur
          adipisicing elit. Earum, sed voluptas facilis facere eveniet nesciunt.
          Provident explicabo aperiam vero repellendus nam fuga eum possimus
          accusantium in tempora. Porro, consequuntur optio?
        </p>
      </div>
      {/* New section */}
      <div>
        <div className="text-center mt-20 relative flex flex-col justify-center items-center">
          <h2 className="font-bold text-8xl text-orange-500/40 py-4 ">OE</h2>
        <h2 className="text-4xl text-orange-600 font-bold absolute" >OUR EVENTS</h2>
        </div>
        
        <div className="flex flex-col md:flex-row justify-center items-center gap-4 ">
          <div className="w-10/12 md:w-1/5 bg-[url('/images/wedding.jpg')] bg-center bg-cover h-60 bg-black/70 text-orange-500 bg-blend-overlay">
            <h3 className="text-2xl text-center font-bold py-4">Wedding Party</h3>
            <p className="text-center text-white">We offer the best quality with reasonable price to make your wedding a memorable one</p>
          </div>
          <div className="w-10/12 md:w-1/5 bg-[url('/images/birthday.jpeg')] bg-center bg-cover h-60 bg-black/70 text-orange-500 bg-blend-overlay">
          <h3 className="text-2xl text-center font-bold py-4">Birthday Party</h3>
            <p className="text-center text-white">We offer the best quality with reasonable price to make your wedding a memorable one</p>
          </div>
          <div className="w-10/12 md:w-1/5 bg-[url('/images/corperate.jpeg')] bg-center bg-cover h-60 bg-black/70 text-orange-500 bg-blend-overlay">
          <h3 className="text-2xl text-center font-bold py-4">Corperate Party</h3>
            <p className="text-center text-white">We offer the best quality with reasonable price to make your wedding a memorable one</p>
          </div>
          <div className="w-10/12 md:w-1/5 bg-[url('/images/others.jpeg')] bg-center bg-cover h-60 bg-black/70 text-orange-500 bg-blend-overlay">
          <h3 className="text-2xl text-center font-bold py-4">Others...</h3>
            <p className="text-center text-white">We offer the best quality with reasonable price to make your wedding a memorable one</p>
          </div>
        </div>
      </div>
      {/* New Section */}
      <div className="border-2 text-center my-20">
      <div className="text-center mt-20 relative flex flex-col justify-center items-center">
          <h2 className="font-bold text-8xl text-orange-500/40 py-4 ">MP</h2>
        <h2 className="text-4xl text-orange-600 font-bold absolute" >MENU AND PACKAGES</h2>
        </div>
       
        <div className="grid md:grid-cols-3 gap-8 w-8/12 mx-auto">
          <Link href=''className="hover:scale-105 group transition-transform duration-200 ease-in-out">
            <div className="w-full bg-[url('/images/din.jpg')] bg-center bg-cover h-48 bg-black/70 text-white bg-blend-overlay flex justify-center items-center">
              <h2 className="text-2xl font-semibold py-4">Banquets Events Menu</h2>
            </div>
          </Link>
          <Link href='' className="hover:scale-105 group transition-transform duration-200 ease-in-out">
            <div className="w-full bg-[url('/images/corperate.jpeg')] bg-center bg-cover h-48 bg-black/70 text-white bg-blend-overlay flex justify-center items-center">
              <h2 className="text-2xl font-semibold py-4">Corperate Menu</h2>
            </div>
          </Link>
          <Link href=''className="hover:scale-105 group transition-transform duration-200 ease-in-out">
            <div className="w-full bg-[url('/images/menu.jpg')] bg-center bg-cover h-48 bg-black/70 text-white bg-blend-overlay flex justify-center items-center">
              <h2 className="text-2xl font-semibold py-4">Buffet Snacks Events Menu</h2>
            </div>
          </Link>
          <Link href='' className="hover:scale-105 group transition-transform duration-200 ease-in-out">
            <div className="w-full bg-[url('/images/pancake.jpg')] bg-center bg-cover h-48 bg-black/70 text-white bg-blend-overlay flex justify-center items-center">
              <h2 className="text-2xl font-semibold py-4">Breakfast Menu</h2>
            </div>
          </Link>
          <Link href='' className="hover:scale-105 group transition-transform duration-200 ease-in-out">
            <div className="w-full bg-[url('/images/gpd.jpg')] bg-center bg-cover h-48 bg-black/70 text-white bg-blend-overlay flex justify-center items-center">
              <h2 className="text-2xl font-semibold py-4">Meeting and Conference Events Menu</h2>
            </div>
          </Link>
          <Link href=''className="hover:scale-105 group transition-transform duration-200 ease-in-out">
            <div className="w-full bg-[url('/images/beverage.jpg')] bg-center bg-cover h-48 bg-black/70 text-white bg-blend-overlay flex justify-center items-center">
              <h2 className="text-2xl font-semibold py-4">Bevarages Menu</h2>
            </div>
          </Link>
        </div>
        <div className="bg-red-400 w-full h-96 mt-20">
          <h2 className="text-center">You may also like</h2>
          <div className="relative overflow-x-hidden w-full h-full">
            <div className="flex justify-center gap-4 mt-8 absolute whitespace-nowrap animate-marquee duration-[15s] w-[200%] will-change-transform">{ menuData.map(i => {
         return <div key={i.id} className="w-full h-full">
      <Image src={i.image} alt={i.title} width={400} height={400} className="w-full h-full" />
    </div>
  })}</div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Cathering;
