import React from 'react'
import Head from 'next/head'
import Link from 'next/link'


const Contact = () => {
  return (
   
    <>
     <Head>
              <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className='border mt-20 mx-auto w-full md:w-10/12 px-8 py-4 shadow-md md:flex items-center'>
      <h1 className='w-full text-4xl font-bold text-gray-900 text-center '>Reach out to Us</h1>
      <form className=' w-full flex flex-col gap-4'>
      <h2 className='font-semibold py-4'>We value your continous patronage, for feedback on our services,complaints or ways we can better serve you please fill out the form below </h2>
        <div>
        <label htmlFor='name'>Name</label>
        <input id='name' type='text' placeholder='Enter name' className="w-full border border-black/50 p-2 outline-none"/>
        </div>
       <div>
       <label>Comment</label>
        <textarea placeholder='Write your comment' rows={4}
              className="w-full border border-black/50 p-2 outline-none">

        </textarea>
       </div>
        <div className=''>
          <button className='w-32 mx-auto block py-2 bg-orange-500 hover:bg-white hover:text-orange-600 shadow-md hover:border text-white font-semibold rounded-md'>Submit</button>
        </div>
      </form>
    </div>
          {/* New section */}
          <div className='pl-4 py-4 w-full md:w-10/12 mx-auto'>
            <h2 className='text-3xl font-bold text-gray-900 py-4'>Cathering services</h2>
            <p>To get a quotation for your events please contact us on:</p>
            <p><span className='font-semibold'>Phone</span>: +2347032873032</p>
           <p><span className='font-semibold'>Email</span>: st.jennyandy@gmail.com</p>
          </div>
             {/* New Section */}
          <div className='px-4 py-4 w-full md:w-10/12 mx-auto'>
            <h2 className='text-3xl font-bold text-gray-900 py-4'>Let us be your host</h2>
            <h2>We would love to host your next birthday or engagement party or maybe just a reunion with old friends </h2>
            <p>Walk-in to our venue to make a reservation and let us handle all the hassle</p>
            <p>You can also make a reservation by phone on any of our numbers</p>
            <p>For dinner reservation, <Link className='border-1 bg-gray-100 text-blue-500 p-1 hover:bg-white hover:text-orange-600' href='/dinning'>Click here</Link></p>
          </div>
         
    </>
   
    
  )
}

export default Contact