import React, {useState, useContext} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { cartApi } from '@/contextAPI'

import { useRouter } from 'next/router'
import { AiOutlineShoppingCart } from 'react-icons/ai'
import {RxHamburgerMenu} from 'react-icons/rx'

const Layout = (props) => {
  const {cart} = useContext(cartApi)
  const router = useRouter()
  
 
  const [toggle, setToggle] = useState(false)
  const handleOrders = () => {
    router.push("/menu")
  }
  const handleCart = () => {
    router.push('/cart')
  }
  const toggleNav = () => {
    setToggle(prev => !prev)
  }
 
   
  return (
      
       <>
      <Head>
              <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col'>
       
        <header className='flex justify-between items-center px-4 py-2 border-2 fixed top-0 bg-white w-screen z-50 '>
          <div className=' flex items-center gap-2'>
            <h1 className='p-2 font-semibold text-xl border-4 border-orange-600'>Forfoods</h1>
            <RxHamburgerMenu onClick={toggleNav} className='md:hidden'/>
          </div>
          <nav className='flex items-center'>
          <button onClick={handleOrders} className='border px-6 py-2 font-medium bg-orange-600 text-white hover:opacity-50'>Order Now</button>
           
            <ul className={toggle ? 'gap-6 px-4 flex flex-col absolute top-16 right-2 bg-white': 'hidden md:flex md:flex-row md:relative md:gap-6 px-4 '}> 
              <li><Link href="/" onClick={() =>setToggle(false)} className='text-lg hover:text-red-500 font-semibold focus:text-red-300'>Home</Link></li>
              <li><Link href="/cathering" onClick={() =>setToggle(false)} className='text-lg  hover:text-red-500 font-semibold focus:text-red-300'>Cathering</Link></li>
              <li><Link href="/dinning" onClick={() =>setToggle(false)} className='text-lg  hover:text-red-500 font-semibold focus:text-red-300'>Dine in</Link></li>
              <li><Link href="/menu" onClick={() =>setToggle(false)} className='text-lg  hover:text-red-500 font-semibold focus:text-red-300'>Menu</Link></li>
              <li><Link href="/contact" onClick={() =>setToggle(false)} className='text-lg  hover:text-red-500 font-semibold focus:text-red-300'>Contact Us</Link></li>
              <li><Link href="activities" onClick={() =>setToggle(false)} className='text-lg  hover:text-red-500 font-semibold focus:text-red-300'>Activities</Link></li>
            </ul>
           {cart.length > 0 &&  <button
              onClick={handleCart}
              className=' px-4 py-4 font-medium bg-white text-orange-600 hover:opacity-80 flex items-center'>
              <AiOutlineShoppingCart /><sup className='p-2 rounded-full border-2 border-orange-600'>{cart.length}</sup></button> }
           
          </nav>
        </header>
        <div className='grow'>
        {props.children}
        </div>
        
        
      </main>
      </>
  )
}

export default Layout